### ISSUE TITLE
Tablet view

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/antiphoner-viewer#11]
Tried to view diva viewer on an iPad and the incipit text and data in the right window is not fully responsive.

**Comment by annakijas1** [comment]
@Otterfan did you get a chance to test it on an iPad again?

**Comment by Otterfan** [comment]
We now have a real tablet view that looks like this:

![image](https://cloud.githubusercontent.com/assets/210404/18353032/a045237c-75ae-11e6-829a-e9f8df071e67.png)

It works on iPads going back to Safari 7.1.

**Comment by annakijas1** [comment]
Awesome!
