### ISSUE TITLE
Incorrect order of Incipits

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/antiphoner-viewer#5]
Folio 002r current json data skips from "Dignum sibi dominus" (row 15 in spdsht) to "Homo dei ducebatur" (row 20 in spdsht) which is messing up the order of the incipits that are pulled in. See screenshots.
![screen shot 2016-08-26 at 2 42 57 pm](https://cloud.githubusercontent.com/assets/6841932/18016669/92908266-6b9b-11e6-9877-4362b232b835.png)

![screen shot 2016-08-26 at 2 41 19 pm](https://cloud.githubusercontent.com/assets/6841932/18016672/96c2e6c6-6b9b-11e6-8693-230209c619c7.png)

**Comment by annakijas1** [comment]
Same issue with "Dilexit Andream" (row 17 spdsht) jumping to "Cumque carnifices" (row 21 spdsht) in json file.
![screen shot 2016-08-26 at 2 48 22 pm](https://cloud.githubusercontent.com/assets/6841932/18016801/4f2cb750-6b9c-11e6-875d-e220c81a4e5b.png)

![screen shot 2016-08-26 at 2 48 00 pm](https://cloud.githubusercontent.com/assets/6841932/18016809/5899de08-6b9c-11e6-83e0-b585bf9350c1.png)

**Comment by Otterfan** [comment]
Yep, it looks like these are issues from the Cantus CSV:

![image](https://cloud.githubusercontent.com/assets/210404/18016910/c894035a-6b9c-11e6-9a25-8efa9816d28a.png)

and 

![image](https://cloud.githubusercontent.com/assets/210404/18017013/53059724-6b9d-11e6-908a-2f2b03654a3c.png)

I'll fix those in our import and look for other duplicates or out-of-orders.

**Comment by Otterfan** [comment]
Fixed in BCDigSchol/antiphoner-site@5147b039d5b89dcd9ffc665a94a190fab0a3a412
