### ISSUE TITLE
Separate searches

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/antiphoner-viewer#8]
Separate tab for "Search Text" (full text and all drop down menus) and "Search Melodies" (volpiano)

**Comment by annakijas1** [comment]
It works the way it is now with all search options in one tab so maybe we should just leave this? @Otterfan

**Comment by Otterfan** [comment]
Yeah, I think with Volpiano not the top option and the line heights normlized it looks OK. I'm going to close this.
